name: Ansible EC2 System Info

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  collect-info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible python3

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install json

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run Ansible Playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
      run: |
        ansible-playbook -i inventory.ini playbook.yml