name: System Information Gathering

on:
  workflow_dispatch:

jobs:
  gather-system-info:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3

    - name: Read IP addresses from input.txt
      id: read_ips
      run: |
        ips=$(tr '\n' ' ' < input.txt)
        echo "IP_ADDRESSES=$ips" >> $GITHUB_ENV

    - name: Copy Python script to runner workspace
      run: |
        # Path relative to the repository root
        cp ./scripts/gather_system_info.py $HOME/workspace/
        ls $HOME/workspace/  # Optionally, list files to verify copy

    - name: Gather and upload system information
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BUCKET_NAME: your-bucket-name
        IP_ADDRESSES: ${{ env.IP_ADDRESSES }}
      run: |
        script_path=$HOME/workspace/gather_system_info.py
        
        # Ensure the script exists in the copied location
        if ! [ -f "$script_path" ]; then
          echo "Error: Script $script_path not found!"
          exit 1
        fi
        
        # Loop through each IP and execute the script
        for ip in $IP_ADDRESSES; do
          echo "Processing IP: $ip"
          python $script_path --ip $ip --bucket $BUCKET_NAME
        done